### PR TITLE
Update AposEditLayout.astro

### LINKED ISSUE #10: Compatibility with ViewTransitions
When using ViewTransitions ([https://docs.astro.build/en/guides/view-transitions/](https://docs.astro.build/en/guides/view-transitions/)), the admin UI disappears when navigating from one page to another - it comes back after a page refresh.

### PR DESCRIPTION
**Pull request by daklik**
## Summary

Add a timestamp based query parameter in order to force the load and execution with view transitions.
Closes #10 

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Review by boutell — CHANGES_REQUESTED** [review]
This will reload a large JS bundle on every page load, yes? I realize it's for editors, but still, we should be able to do better... we should be able to get the release id from Apostrophe and incorporate that into the URL.

`apos.asset.getReleaseId();`

That would address the possibility of old Apostrophe admin UI assets without reloading them constantly.

But I think you're actually looking to force this code to re-execute on every page load, for reasons other than stale code after a new deploy. I'm not sure why though.

I think the question we should be trying to answer is what piece of code really needs to re-execute and why, and if necessary how to re-execute it on page load without re-fetching it at considerable expense from the server.

**Comment by boutell** [comment]
These view transitions are a substitute for full page loads and they repopulate the whole page with markup Apostrophe hasn't seen yet, correct? That's the core of the issue?

**Comment by boutell** [comment]
The apos bundle ends with this code:

```
if (document.readyState !== 'loading') {
  setTimeout(invoke, 0);
} else {
  window.addEventListener('DOMContentLoaded', invoke);
}
function invoke() {
  AposI18nCrossDomainSession_0App();
  AposBusy_1App();
  AposAdminBar_2App();
  AposNotification_3App();
  AposLogin_4App();
  AposDoc_5App();
  AposModals_6App();
  index_7App();
  AposAreas_8App();
  AposRichTextPermalinkResolver_9App();
  AposBusEvent_10App();
  TheAposSettings_11App();
  AposImageRelationshipQueryFilter_12App();
  AposCommandMenu_13App();
  index_14App();
}
```

I suspect what you really want to do is re-invoke that function.

But it is imported as an ES module, so there is no way to access it from the outside unless we attach something to `window`.

So what I suggest is that in `asset/index.js` in core, you try changing `function invoke() {...}` to `window.apos.invoke = () => {...}`, move and update the logic that invokes it to use `apos.invoke`, and then try calling `apos.invoke()` from a handler that fires on these view transitions.

**Comment by daklik** [comment]
As mentioned in our side discussion, I tried to execute this invoke on some specific astro page load event, but it's not working properly - we miss the CSS part of all.
I agree that this modification means reload of the full bundle for editors in each page switch - but without that, they don't even get back the admin UI in a page navigation.
I feel like we could go with that first easy implementation, getting the expected behaviour back but with in mind this performance issue for them, and then deep dive into the more deeper issue in the core of Apostrophe.

**Review by boutell — APPROVED** [review]
Accepting for now, will open a ticket about a more efficient long term solution

**Pull request merged**
